apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-tohar
  namespace: tohar
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
